project_army/project_army/urls.py
# -*- coding: utf-8 -*-

"""project_army URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""


from django.conf.urls import url
from django.contrib import admin

from django.contrib.auth import views as auth_views

from project_army.views import root_page, signup
from character_sheet.views import characters_list, characters_detail, characters_new, equipment_list, equipment_detail, equipment_new

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', root_page, name='home'),
    url(r'^characters/$', characters_list),
    url(r'^characters/new/$', characters_new),
    url(r'^characters/(?P<id>\d+)/$', characters_detail),
    url(r'^characters/update/$', characters_list),
    url(r'^characters/delete/$', characters_list),
    url(r'^equipment/$', equipment_list),
    url(r'^equipment/new/$', equipment_new),
    url(r'^equipment/(?P<id>\d+)/$', equipment_detail),
    url(r'^equipment/update/$', characters_list),
    url(r'^equipment/delete/$', characters_list),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', signup, name='signup'),
]

project_army/character_sheet/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
# Create your models here.


class Character_sheet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    name = models.CharField(max_length=40)
    GENDER_CHOICES = (
        ('M', 'Mężczyzna'),
        ('F', 'Kobieta'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
    RACE_CHOICES = (
        ('H', 'Człowiek'),
        ('O', 'Ork'),
        ('E', 'Elf'),
        ('D', 'Krasnolud'),
    )
    race = models.CharField(max_length=1, choices=RACE_CHOICES, default='H')
    CLASS_CHOICES = (
        ('W', 'Wojownik'),
        ('R', 'Łotrzyk'),
        ('M', 'Mag'),
        ('C', 'Kusznik'),
    )
    class_x = models.CharField(max_length=1, choices=CLASS_CHOICES, default='W')
    gold = models.IntegerField(default=1000)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


class Equipment(models.Model):
    name = models.CharField(max_length=40)
    price = models.IntegerField(default=0)
    WEAPON_TYPE_CHOICES = (
        ('M', 'Broń ręczna'),
        ('D', 'Broń zasięgowa'),
        ('A', 'Pancerz/Ubiór'),
        ('C', 'Użytkowy'),
    )
    weapon_type = models.CharField(max_length=1, choices=WEAPON_TYPE_CHOICES, default='C')
    description = models.TextField(max_length=300)
    owned_by = models.ManyToManyField(Character_sheet)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name

project_army/character_sheet/forms.py
from django import forms

from .models import Character_sheet, Equipment

class Character_sheet_form(forms.ModelForm):
    class Meta:
        model = Character_sheet
        fields = [
            "name",
            "gender",
            "race",
            "class_x"
        ]
        
class Equipment_form(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = [
            "name",
            "price",
            "weapon_type",
            "description"
        ]

project_army/character_sheet/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.template import loader
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.models import User, Group

from .models import Character_sheet, Equipment
from .forms import Character_sheet_form, Equipment_form
# Create your views here.


# CHARACTERS
# LIST
def characters_list(request):
    querydata = Character_sheet.objects.all()
    passed_data = {
        "querydata": querydata,
        "title": "Lista Postaci"
    }
    return render(request, "characters/list.html", passed_data)


# DETAIL
def characters_detail(request, id):
    instance = get_object_or_404(Character_sheet, id=id)
    equipment = instance.equipment_set.all()
    passed_data = {
        "instance": instance,
        "title": instance.name,
        "equipment": equipment
    }
    return render(request, "characters/detail.html", passed_data)


# CREATE
def characters_new(request):

    if request.user.groups.filter(name="Player").exists():

        form = Character_sheet_form(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect(characters_list)
        passed_data = {
            "form": form,
            "title": "Nowa Postać"
        }
        return render(request, "characters/new.html", passed_data)
    else:
        raise Http404


# EQUIPMENT
# LIST
def equipment_list(request):
    querydata = Equipment.objects.all()
    passed_data = {
        "querydata": querydata,
        "title": "Lista Ekwipunku"
    }
    return render(request, "equipment/list.html", passed_data)


# DETAIL
def equipment_detail(request, id):
    instance = get_object_or_404(Equipment, id=id)
    characters = []
    if request.user.groups.filter(name="Player").exists():
        characters = get_list_or_404(Character_sheet, user=request.user)
    if request.method == "POST":
        character_id = request.POST.get("character_name")
        character_buy = get_object_or_404(Character_sheet, id=character_id)
        if not(instance.owned_by.filter(name=character_buy)):
            if character_buy.gold >= instance.price:  # if afford
                current_gold = character_buy.gold - instance.price
                instance.owned_by.add(character_buy)
                instance.save()
                Character_sheet.objects.filter(id=character_buy.id).update(gold=current_gold)
                messages.success(request, "Kupiono!")
            else:
                messages.error(request, "Za mało pieniędzy!")
        else:
            messages.error(request, "Ta postać już to posiada, NIE KUPIONO!")

    passed_data = {
        "instance": instance,
        "title": instance.name,
        "characters": characters
    }
    return render(request, "equipment/detail.html", passed_data)


# CREATE
def equipment_new(request):
    if request.user.groups.filter(name="Game Master").exists():
        form = Equipment_form(request.POST or None)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect(equipment_list)
        passed_data = {
            "form": form,
            "title": "Nowy Ekwipunek"
        }
        return render(request, "equipment/new.html", passed_data)
    else:
        raise Http404

project_army/project_army/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm


def root_page(request):
    return render(request, "home.html")


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

project_army/templates/characters/detail.html
{% extends "index.html" %}

{% block content %}
<div class="slimmer">
Postać użytkownika: {{ instance.user.username }}</br></br>

<table class="slimmer table table-borderless">
    <tr>
        <th class="info col-xs-4">Płeć:</th>
        <th>{{ instance.get_gender_display }}</th>
    </tr>
    <tr>
        <th class="info col-xs-4">Rasa:</th>
        <th>{{ instance.get_race_display }}</th>
    </tr>
    <tr>
        <th class="info col-xs-4">Klasa:</th>
        <th>{{ instance.get_class_x_display }}</th>
    </tr>
    <tr>
        <th class="info col-xs-4">Posiadane złoto:</th>
        <th>{{ instance.gold }}</th>
    </tr>
    <tr>
        <th class="info col-xs-4">Posiadany ekwipunek:</th>
        <th><table class="table">
        {% for equ in equipment %}
            <tr>
                <th class="info col-xs-7"><a href="/equipment/{{ equ.id }}">{{ equ.name }}</a></th>
                <th>{{ equ.get_weapon_type_display }}</th>
            </tr>
        {% endfor %}
        </table>
        </th>
    </tr>
</table>


</div>

{% endblock %}

project_army/templates/characters/list.html
{% extends "index.html" %}

{% block content %}
<div>
<table class="table table-striped table-hover">
<thead>
  <tr class="info">
    <th class="text-center">Imię</th>
    <th class="text-center">Płeć</th> 
    <th class="text-center">Rasa</th>
    <th class="text-center">Klasa</th>
  </tr>
</thead>
<tbody>
{% for obj in querydata %}
<tr>
    <th class="text-center"><a href="/characters/{{ obj.id }}">{{ obj.name }}</a></th>
    <th class="text-center">{{ obj.get_gender_display }}</th>
    <th class="text-center">{{ obj.get_race_display }}</th>
    <th class="text-center">{{ obj.get_class_x_display }}</th>
</tr>
{% endfor %}
</tbody>
</table>
</div>
    
{% endblock %}
    

project_army/templates/characters/new.html
{% extends "index.html" %}

{% block content %}

<form method='POST' action=''>{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Stwórz Postać' />
</form>

{% endblock %}
    

project_army/templates/equipment/detail.html
{% extends "index.html" %}

{% block content %}

<table class="slimmer table table-borderless">
    <tr>
        <th class="info col-xs-2">Cena:</th>
        <th>{{ instance.price }}</th>
    </tr>
    <tr>
        <th class="info col-xs-2">Typ:</th>
        <th>{{ instance.get_weapon_type_display }}</th>
    </tr>
    <tr>
        <th class="info col-xs-2">Opis:</th>
        <th>{{ instance.description }} </th>
    </tr>
</table>

{% if user.groups.all.0.name == "Player" %}
    <form method='POST' action=''>{% csrf_token %}
    <button class="btn btn-warning" type=submit>Kup Dla:</button>
    <select name="character_name" class="btn btn-warning">
    {% for character in characters %}
        <option value={{ character.id }}>{{ character.name }}</option>
    {% endfor %}
    </select>
    </form>

{% endif %}
{% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}


{% endblock %}

project_army/templates/equipment/list.html
{% extends "index.html" %}

{% block content %}
<div>
<table class="table table-striped table-hover">
<thead>
  <tr class="info">
    <th class="text-center">Nazwa</th>
    <th class="text-center">Cena</th> 
    <th class="text-center">Rodzaj</th>
  </tr>
</thead>
<tbody>
{% for obj in querydata %}
<tr>
    <th class="text-center"><a href="/equipment/{{ obj.id }}">{{ obj.name }}</a></th>
    <th class="text-center">{{ obj.price }}</th>
    <th class="text-center">{{ obj.get_weapon_type_display }}</th>

</tr>
{% endfor %}
</tbody>
</table>
</div>

{% endblock %}

project_army/templates/equipment/new.html
{% extends "index.html" %}

{% block content %}

<form method='POST' action=''>{% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Stwórz Ekwipunek' />
</form>

{% endblock %}
    

project_army/templates/home.html
{% extends "index.html" %}

{% block content %}

<h1>Pomoc przy organizacji postaci.</h1>
Nie zabieraj czasu sesji, ogarnij postac już teraz!


{% endblock %}
    

project_army/templates/index.html
<!--DOCTYPE html -->
<html lang="pl">
    <head>
        <meta charset="utf-16" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" type="text/css" />
        <style>
            body { padding-top: 50px; }
            .slimmer {
                max-width: 500px;
            }
        </style>
    </head>

    <body>

        {% include "menu.html" %}
                <h1>{{ title }}</h1>
        {% block content %} {% endblock %}

    </body>




</html>

project_army/templates/menu.html
<div class="navbar navbar-default navbar-fixed-top" id="Ttopnav">
    <div style="float:left;">
      <a class="btn btn-default navbar-btn" href="/">Home</a>
      <a class="btn btn-default navbar-btn" href="/characters">Lista Postaci</a>
      <a class="btn btn-default navbar-btn" href="/equipment">Lista Ekwipunku</a>
        {% if user.groups.all.0.name == "Player" %}
            <a class="btn btn-default navbar-btn" href="/characters/new">Nowa postać</a>
        {% endif %}
        {% if user.groups.all.0.name == "Game Master" %}
            <a class="btn btn-default navbar-btn" href="/equipment/new">Nowy ekwipunek</a>
        {% endif %}
    </div>
    <div style="float:right;">
        {% if user.is_authenticated %}
            <span>Zalogowano jako: {{ user.username }}  </span> 
            <a class="btn btn-default navbar-btn" href="/logout">Wyloguj</a>
        
        {% else %}
            <a class="btn btn-default navbar-btn" href="/login">Zaloguj</a>
            <a class="btn btn-default navbar-btn" href="/signup">Zarejestruj</a>
        {% endif %}
    </div>
</div> 